name: ddev-mscacceptancetests
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        name: ddev-mscacceptancetests_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.4:v1.22.5
                gid: "20"
                uid: "501"
                username: admin
            context: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-mscacceptancetests-db
        environment:
            COLUMNS: "202"
            DDEV_DATABASE: mariadb:10.4
            DDEV_DATABASE_FAMILY: mysql
            DDEV_HOSTNAME: mscacceptancetests.ddev.site
            DDEV_PHP_VERSION: "7.4"
            DDEV_PRIMARY_URL: https://mscacceptancetests.ddev.site
            DDEV_PROJECT: mscacceptancetests
            DDEV_PROJECT_TYPE: php
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: mscacceptancetests
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: amd64
            GOOS: darwin
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "56"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/mscacceptancetests-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: ""
            USER: admin
        healthcheck:
            interval: 1s
            retries: 120
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: mscacceptancetests-db
        image: ddev/ddev-dbserver-mariadb-10.4:v1.22.5-mscacceptancetests-built
        labels:
            com.ddev.app-type: php
            com.ddev.approot: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests
            com.ddev.platform: ddev
            com.ddev.site-name: mscacceptancetests
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: "501:20"
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/admin
    selenium:
        command:
            - /opt/bin/entry_point.sh
        container_name: ddev-mscacceptancetests-selenium
        entrypoint:
            - /opt/bin/entry_point.sh
        environment:
            HTTP_EXPOSE: "4444"
            VIRTUAL_HOST: mscacceptancetests.ddev.site
        external_links:
            - ddev-router:mscacceptancetests.ddev.site
        image: selenium/standalone-chrome:4.16.1-20231212
        labels:
            com.ddev.approot: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests
            com.ddev.site-name: mscacceptancetests
        networks:
            ddev_default: null
            default: null
        ports:
            - mode: ingress
              protocol: tcp
              target: 4444
            - mode: ingress
              protocol: tcp
              published: "7900"
              target: 7900
        shm_size: "2147483648"
    web:
        build:
            args:
                BASE_IMAGE: ddev/ddev-webserver:v1.22.5
                DDEV_PHP_VERSION: "7.4"
                gid: "20"
                uid: "501"
                username: admin
            context: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-mscacceptancetests-web
        environment:
            COLUMNS: "202"
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.4
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: public
            DDEV_FILES_DIR: ""
            DDEV_FILES_DIRS: ""
            DDEV_HOSTNAME: mscacceptancetests.ddev.site
            DDEV_MUTAGEN_ENABLED: "true"
            DDEV_PHP_VERSION: "7.4"
            DDEV_PRIMARY_URL: https://mscacceptancetests.ddev.site
            DDEV_PROJECT: mscacceptancetests
            DDEV_PROJECT_TYPE: php
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: mscacceptancetests
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.22.5
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: apache-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: public
            DRUSH_ALLOW_XDEBUG: "1"
            DRUSH_OPTIONS_URI: https://mscacceptancetests.ddev.site
            GOARCH: amd64
            GOOS: darwin
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "56"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/mscacceptancetests-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=mscacceptancetests.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: ""
            USER: admin
            VIRTUAL_HOST: mscacceptancetests.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:mscacceptancetests.ddev.site
        healthcheck:
            interval: 1s
            retries: 120
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: mscacceptancetests-web
        image: ddev/ddev-webserver:v1.22.5-mscacceptancetests-built
        labels:
            com.ddev.app-type: php
            com.ddev.approot: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests
            com.ddev.platform: ddev
            com.ddev.site-name: mscacceptancetests
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
        restart: "no"
        user: "501:20"
        volumes:
            - source: project_mutagen
              target: /var/www
              type: volume
              volume:
                nocopy: true
            - source: project_mutagen
              target: /tmp/project_mutagen
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              read_only: true
              source: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /Users/admin/Projects/workspace/acceptanceTestsProjects/DDEV/mscacceptancetests/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: mscacceptancetests-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
    project_mutagen:
        external: true
        name: mscacceptancetests_project_mutagen
